# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6acdd62ea1518d76d9e7d24358163a8f4e61be2fa82e2b5152c9f199c09c09342d46ebf0807eb58a5159a1a70cc883fc4b35b5b4c17eb50fcd0f4b98281bb1a3

test:
  secret_key_base: 77746b68449cc8606840b76fe981e89ca9f4dfe15ddb9992b0c074f3696103b84717d8cb478376ede59244516c799b5307ac5256f0dd6ee1c84cefe24a846523

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
